github:
  api-url: https://api.github.com/repos/CVEProject/cvelistV5/commits?sha=main&per_page=50
  raw-url: https://raw.githubusercontent.com/CVEProject/cvelistV5/main/cves/

credentials:
  google-chat-webhook: https://chat.googleapis.com/v1/spaces/

mysql:
  host: 
  user: 
  password: 
  database: cve_alert

